- name: variables at playlevel
  hosts: local
  connections: local
  vars:
    COURSENAME: devops
    DURATION: 10hrs
    TUTOR: SHIVA
  tasks:
  - name: variables
    ansible.builtin.debug:
    msg: "course name is {{ COURSENAME }},duration of course is {{ DURATION }} and tutor is {{ TUTOR }}"