- name: configuring  mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: installing mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: started
      enable: yes  
  

    